DROP TABLE IF EXISTS `pokemon` CASCADE;

CREATE TABLE pokemon(
	id INT AUTO_INCREMENT,
	name VARCHAR(255) UNIQUE NOT NULL,
	type VARCHAR(255) NOT NULL,
	moveone VARCHAR(255) NOT NULL,
	movetwo VARCHAR(255) NOT NULL,
	PRIMARY KEY (id)
);