DROP TABLE IF EXISTS `pokemon` CASCADE;

CREATE TABLE pokemon(
	id INT AUTO_INCREMENT,
	name VARCHAR(255) UNIQUE NOT NULL,
	type VARCHAR(255) NOT NULL,
	move_one VARCHAR(255) NOT NULL,
	move_two VARCHAR(255) NOT NULL,
	PRIMARY KEY (id)
);